name: "Fundy"
description: "Gestion des finances de la maison"
version: "0.1.0"
slug: "fundy"
webui: http://[HOST]:[PORT:8888]
init: false
ports:
  8888/tcp: 8888
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
